<?xml version="1.0" standalone="yes"?>
<NewDataSet>
  <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Table1" msdata:UseCurrentLocale="true">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="Table1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Error_Type" type="xs:string" minOccurs="0" />
                <xs:element name="Error_DateTime" type="xs:dateTime" minOccurs="0" />
                <xs:element name="Error_Description" type="xs:string" minOccurs="0" />
                <xs:element name="Error_Source" type="xs:string" minOccurs="0" />
                <xs:element name="Error_Stack_Trace" type="xs:string" minOccurs="0" />
                <xs:element name="Error_Caused_By_Method" type="xs:string" minOccurs="0" />
                <xs:element name="Optional_Text_1" type="xs:string" minOccurs="0" />
                <xs:element name="Optional_Text_2" type="xs:string" minOccurs="0" />
                <xs:element name="Optional_Text_3" type="xs:string" minOccurs="0" />
                <xs:element name="NombreUsuario" type="xs:string" minOccurs="0" />
                <xs:element name="HostName" type="xs:string" minOccurs="0" />
                <xs:element name="IPAddress" type="xs:string" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:complexType>
    </xs:element>
  </xs:schema>
  <Table1>
    <Error_Type>System.Collections.ListDictionaryInternal</Error_Type>
    <Error_DateTime>2021-02-25T16:16:46.4032707-05:00</Error_DateTime>
    <Error_Description>Índice fuera de los límites de la matriz.</Error_Description>
    <Error_Source>AplicacionSistemaVentura</Error_Source>
    <Error_Stack_Trace>   en AplicacionSistemaVentura.InterfazPrincipal.VerificarAlertas() en C:\Users\gparedes\Desktop\VSMONE\VSMONE_FUENTE\HANA\AplicacionSistemaVentura\InterfazPrincipal.xaml.cs:línea 257</Error_Stack_Trace>
    <Error_Caused_By_Method>Void VerificarAlertas()</Error_Caused_By_Method>
    <Optional_Text_1 />
    <Optional_Text_2 />
    <Optional_Text_3 />
    <NombreUsuario>MANAGER</NombreUsuario>
    <HostName>WIN-Q3O0BSPVASQ</HostName>
    <IPAddress>192.168.1.40</IPAddress>
  </Table1>
  <Table1>
    <Error_Type>System.Collections.ListDictionaryInternal</Error_Type>
    <Error_DateTime>2021-02-25T17:59:01.3832694-05:00</Error_DateTime>
    <Error_Description>No se puede reconocer la cadena como valor DateTime válido.</Error_Description>
    <Error_Source>mscorlib</Error_Source>
    <Error_Stack_Trace>   en System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   en System.Convert.ToDateTime(String value)
   en AplicacionSistemaVentura.PAQ04_Reportes.ReporteKPIMant.GeneraExcel() en C:\Users\gparedes\Desktop\VSMONE\VSMONE_FUENTE\HANA\AplicacionSistemaVentura\PAQ04-Reportes\ReporteKPIMant.xaml.cs:línea 95</Error_Stack_Trace>
    <Error_Caused_By_Method>System.DateTime Parse(System.String, System.Globalization.DateTimeFormatInfo, System.Globalization.DateTimeStyles)</Error_Caused_By_Method>
    <Optional_Text_1 />
    <Optional_Text_2 />
    <Optional_Text_3 />
    <NombreUsuario>MANAGER</NombreUsuario>
    <HostName>WIN-Q3O0BSPVASQ</HostName>
    <IPAddress>192.168.1.40</IPAddress>
  </Table1>
  <Table1>
    <Error_Type>System.Collections.ListDictionaryInternal</Error_Type>
    <Error_DateTime>2021-02-25T18:07:06.5457266-05:00</Error_DateTime>
    <Error_Description>No se puede reconocer la cadena como valor DateTime válido.</Error_Description>
    <Error_Source>mscorlib</Error_Source>
    <Error_Stack_Trace>   en System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   en System.Convert.ToDateTime(String value)
   en AplicacionSistemaVentura.PAQ04_Reportes.ReporteKPIMant.GeneraExcel() en C:\Users\gparedes\Desktop\VSMONE\VSMONE_FUENTE\HANA\AplicacionSistemaVentura\PAQ04-Reportes\ReporteKPIMant.xaml.cs:línea 95</Error_Stack_Trace>
    <Error_Caused_By_Method>System.DateTime Parse(System.String, System.Globalization.DateTimeFormatInfo, System.Globalization.DateTimeStyles)</Error_Caused_By_Method>
    <Optional_Text_1 />
    <Optional_Text_2 />
    <Optional_Text_3 />
    <NombreUsuario>MANAGER</NombreUsuario>
    <HostName>WIN-Q3O0BSPVASQ</HostName>
    <IPAddress>192.168.1.40</IPAddress>
  </Table1>
  <Table1>
    <Error_Type>System.Collections.ListDictionaryInternal</Error_Type>
    <Error_DateTime>2021-02-25T18:27:42.0449952-05:00</Error_DateTime>
    <Error_Description>Excepción de HRESULT: 0x800A03EC</Error_Description>
    <Error_Source />
    <Error_Stack_Trace>   en System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData&amp; msgData)
   en Microsoft.Office.Interop.Excel.Range.get_Range(Object Cell1, Object Cell2)
   en AplicacionSistemaVentura.PAQ04_Reportes.ReporteKPIMant.GeneraExcel() en C:\Users\gparedes\Desktop\VSMONE\VSMONE_FUENTE\HANA\AplicacionSistemaVentura\PAQ04-Reportes\ReporteKPIMant.xaml.cs:línea 113</Error_Stack_Trace>
    <Error_Caused_By_Method>System.Object ForwardCallToInvokeMember(System.String, System.Reflection.BindingFlags, System.Object, Int32[], System.Runtime.Remoting.Proxies.MessageData ByRef)</Error_Caused_By_Method>
    <Optional_Text_1 />
    <Optional_Text_2 />
    <Optional_Text_3 />
    <NombreUsuario>MANAGER</NombreUsuario>
    <HostName>WIN-Q3O0BSPVASQ</HostName>
    <IPAddress>192.168.1.40</IPAddress>
  </Table1>
  <Table1>
    <Error_Type>System.Collections.ListDictionaryInternal</Error_Type>
    <Error_DateTime>2021-02-25T18:30:32.0666004-05:00</Error_DateTime>
    <Error_Description>Excepción de HRESULT: 0x800A03EC</Error_Description>
    <Error_Source />
    <Error_Stack_Trace>   en System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData&amp; msgData)
   en Microsoft.Office.Interop.Excel.Range.get_Range(Object Cell1, Object Cell2)
   en AplicacionSistemaVentura.PAQ04_Reportes.ReporteKPIMant.GeneraExcel() en C:\Users\gparedes\Desktop\VSMONE\VSMONE_FUENTE\HANA\AplicacionSistemaVentura\PAQ04-Reportes\ReporteKPIMant.xaml.cs:línea 113</Error_Stack_Trace>
    <Error_Caused_By_Method>System.Object ForwardCallToInvokeMember(System.String, System.Reflection.BindingFlags, System.Object, Int32[], System.Runtime.Remoting.Proxies.MessageData ByRef)</Error_Caused_By_Method>
    <Optional_Text_1 />
    <Optional_Text_2 />
    <Optional_Text_3 />
    <NombreUsuario>MANAGER</NombreUsuario>
    <HostName>WIN-Q3O0BSPVASQ</HostName>
    <IPAddress>192.168.1.40</IPAddress>
  </Table1>
</NewDataSet>